/*
 * Copyright (c) 2019, Arm Limited and affiliates.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#ifndef WISUN_TEST_CERTIFICATES_H_
#define WISUN_TEST_CERTIFICATES_H_

const uint8_t WISUN_ROOT_CERTIFICATE[] = {
#if 0
    /** Global Sign Root CA **/
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIICIDCCAcagAwIBAgIBATAKBggqhkjOPQQDAjB1MQswCQYDVQQGEwJCRTEZMBcG\r\n"
    "A1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9yIFRlc3QgVXNlIE9u\r\n"
    "bHkxLzAtBgNVBAMTJkdsb2JhbFNpZ24gV2ktU1VOIEZBTiBFQ0MgVGVzdCBSb290\r\n"
    "IENBMCAXDTE4MDcxODAwMDAwMFoYDzk5OTkxMjMxMjM1OTU5WjB1MQswCQYDVQQG\r\n"
    "EwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9yIFRl\r\n"
    "c3QgVXNlIE9ubHkxLzAtBgNVBAMTJkdsb2JhbFNpZ24gV2ktU1VOIEZBTiBFQ0Mg\r\n"
    "VGVzdCBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEp5HbQNUb1bW4\r\n"
    "LnUfs77YXysSp+fXXomez+pnzXIb4FJP94knwauyoMd99BsmW/fK/yHzk6Rs4Fma\r\n"
    "T5m7eRpll6NFMEMwDgYDVR0PAQH/BAQDAgIEMBIGA1UdEwEB/wQIMAYBAf8CAQIw\r\n"
    "HQYDVR0OBBYEFD0qd4ApGSsRSUwEnFv9fIyYnH+SMAoGCCqGSM49BAMCA0gAMEUC\r\n"
    "IQDjD8vQ8PbGY+MCP5e4PW0O0ValmtnVg4DXoGYRz+tioQIgGpHT7NmOHtEg4HRG\r\n"
    "BJe60OcyxFjpDsp/R2pGArN9iuE=\r\n"
    "-----END CERTIFICATE-----"
#else
    /** Wi-SUN Test Root CA **/
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBojCCAUmgAwIBAgIFAPf29t8wCgYIKoZIzj0EAwIwMTEOMAwGA1UECgwFV2lT\r\n"
    "VU4xEzARBgNVBAMMCldpU1VOIFJvb3QxCjAIBgNVBAUTATEwIBcNMTcwNzA0MjEw\r\n"
    "NDAyWhgPOTk5OTEyMzEyMzU5NTlaMDExDjAMBgNVBAoMBVdpU1VOMRMwEQYDVQQD\r\n"
    "DApXaVNVTiBSb290MQowCAYDVQQFEwExMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD\r\n"
    "QgAEVrJidrjt1nWFVA/VOA/1XKARMBv9t+9XbnErRKJhwudMEUguImA6Ns5TS6o6\r\n"
    "wDDGjYF6JzO1htL1+MTNFkId+KNMMEowDwYDVR0TAQH/BAUwAwEB/zARBgNVHQ4E\r\n"
    "CgQIQP089aoIBgswDgYDVR0PAQH/BAQDAgEGMBQGA1UdIAEB/wQKMAgwBgYEVR0g\r\n"
    "ADAKBggqhkjOPQQDAgNHADBEAiBYqSiYL0Tu8D/zzU8TajVkzKMw6qkku+UIezPn\r\n"
    "2Tv6rAIgP5+YwqTLC9QTfuz2/XN6Ta5Hd4zgyLSvc1BXm94r06k=\r\n"
    "-----END CERTIFICATE-----"
#endif
};

const uint8_t WISUN_GS_ROOT_CERTIFICATE_1[] = {
"-----BEGIN CERTIFICATE-----\r\n"
"MIICXjCCAgOgAwIBAgIEGAcYAjAKBggqhkjOPQQDAjB/MQswCQYDVQQGEwJCRTEZ\r\n"
"MBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9yIFRlc3QgVXNl\r\n"
"IE9ubHkxOTA3BgNVBAMTMEdsb2JhbFNpZ24gV2ktU1VOIEZBTiBFQ0MgVGVzdCBN\r\n"
"YW51ZmFjdHVyZXIgQ0EgMTAgFw0xODA3MTgwMDAwMDBaGA85OTk5MTIzMTIzNTk1\r\n"
"OVowgYMxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9iYWxTaWduIG52LXNhMRow\r\n"
"GAYDVQQLExFGb3IgVGVzdCBVc2UgT25seTE9MDsGA1UEAxM0R2xvYmFsU2lnbiBX\r\n"
"aS1TVU4gRkFOIEVDQyBUZXN0IFN1Yi1NYW51ZmFjdHVyZXIgQ0EgMTBZMBMGByqG\r\n"
"SM49AgEGCCqGSM49AwEHA0IABEtsbzInynM0ddFwhBMlrZF/b8QJOS8rR6Ji4aSq\r\n"
"8fIjK+9cyMPTwnxaCSZUvj+IjqM1fcossLTcvQJTGr8ZiRajZjBkMA4GA1UdDwEB\r\n"
"/wQEAwICBDASBgNVHRMBAf8ECDAGAQH/AgEAMB0GA1UdDgQWBBQ3ttkOUJkFBUV3\r\n"
"L09XhhFkvRu9vDAfBgNVHSMEGDAWgBSB8SepzJmMBati+8zAm50esXEhqzAKBggq\r\n"
"hkjOPQQDAgNJADBGAiEAv3SUEAVVEVbu5LIAP9IC7bgM3nZFLXsCCqK/NvifL+8C\r\n"
"IQC0IkpgzHopVq84LtxKr8gnIp8rnsIRUTL53Go2LbQ3PQ==\r\n"
"-----END CERTIFICATE-----\r\n"
};

const uint8_t WISUN_GS_ROOT_CERTIFICATE_2[] = {
"-----BEGIN CERTIFICATE-----\r\n"
"MIICTzCCAfSgAwIBAgIEGAcYATAKBggqhkjOPQQDAjB1MQswCQYDVQQGEwJCRTEZ\r\n"
"MBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9yIFRlc3QgVXNl\r\n"
"IE9ubHkxLzAtBgNVBAMTJkdsb2JhbFNpZ24gV2ktU1VOIEZBTiBFQ0MgVGVzdCBS\r\n"
"b290IENBMCAXDTE4MDcxODAwMDAwMFoYDzk5OTkxMjMxMjM1OTU5WjB/MQswCQYD\r\n"
"VQQGEwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9y\r\n"
"IFRlc3QgVXNlIE9ubHkxOTA3BgNVBAMTMEdsb2JhbFNpZ24gV2ktU1VOIEZBTiBF\r\n"
"Q0MgVGVzdCBNYW51ZmFjdHVyZXIgQ0EgMTBZMBMGByqGSM49AgEGCCqGSM49AwEH\r\n"
"A0IABELV4UWWmobdLAWUmawJqMV6/IbCTwEyAAuuj3zhYunZsLFJq7oThLf8S8l8\r\n"
"+L19ActTDTcE40dRamCjtgpyG7ejZjBkMA4GA1UdDwEB/wQEAwICBDASBgNVHRMB\r\n"
"Af8ECDAGAQH/AgEBMB0GA1UdDgQWBBSB8SepzJmMBati+8zAm50esXEhqzAfBgNV\r\n"
"HSMEGDAWgBQ9KneAKRkrEUlMBJxb/XyMmJx/kjAKBggqhkjOPQQDAgNJADBGAiEA\r\n"
"yDZk9pKX8O3xYIURThYWG3dcS2kOIdKuP2tJ4nwMG4UCIQCzRPcY8jAjLqThArsB\r\n"
"K+Sc8kKdRCayEfN0cJyGVTjGmw==\r\n"
"-----END CERTIFICATE-----\r\n"
};

const uint8_t WISUN_GS_ROOT_CERTIFICATE_3[] = {
"-----BEGIN CERTIFICATE-----\r\n"
"MIICIDCCAcagAwIBAgIBATAKBggqhkjOPQQDAjB1MQswCQYDVQQGEwJCRTEZMBcG\r\n"
"A1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9yIFRlc3QgVXNlIE9u\r\n"
"bHkxLzAtBgNVBAMTJkdsb2JhbFNpZ24gV2ktU1VOIEZBTiBFQ0MgVGVzdCBSb290\r\n"
"IENBMCAXDTE4MDcxODAwMDAwMFoYDzk5OTkxMjMxMjM1OTU5WjB1MQswCQYDVQQG\r\n"
"EwJCRTEZMBcGA1UEChMQR2xvYmFsU2lnbiBudi1zYTEaMBgGA1UECxMRRm9yIFRl\r\n"
"c3QgVXNlIE9ubHkxLzAtBgNVBAMTJkdsb2JhbFNpZ24gV2ktU1VOIEZBTiBFQ0Mg\r\n"
"VGVzdCBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEp5HbQNUb1bW4\r\n"
"LnUfs77YXysSp+fXXomez+pnzXIb4FJP94knwauyoMd99BsmW/fK/yHzk6Rs4Fma\r\n"
"T5m7eRpll6NFMEMwDgYDVR0PAQH/BAQDAgIEMBIGA1UdEwEB/wQIMAYBAf8CAQIw\r\n"
"HQYDVR0OBBYEFD0qd4ApGSsRSUwEnFv9fIyYnH+SMAoGCCqGSM49BAMCA0gAMEUC\r\n"
"IQDjD8vQ8PbGY+MCP5e4PW0O0ValmtnVg4DXoGYRz+tioQIgGpHT7NmOHtEg4HRG\r\n"
"BJe60OcyxFjpDsp/R2pGArN9iuE=\r\n"
"-----END CERTIFICATE-----"
};

const uint8_t WISUN_MCA_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIByzCCAXCgAwIBAgIFAInnL70wCgYIKoZIzj0EAwIwMTEOMAwGA1UECgwFV2lT\r\n"
    "VU4xEzARBgNVBAMMCldpU1VOIFJvb3QxCjAIBgNVBAUTATEwIBcNMjEwNTI5MjAx\r\n"
    "OTI0WhgPOTk5OTEyMzEyMzU5NTlaMDoxCzAJBgNVBAYTAlVTMQswCQYDVQQKDAJU\r\n"
    "STESMBAGA1UEAwwJV2lTVU4gTUNBMQowCAYDVQQFEwEyMFkwEwYHKoZIzj0CAQYI\r\n"
    "KoZIzj0DAQcDQgAEff6D5/8TiDCHY/C66gZTnQ8eQiDpSrZqheOm8LeRUT9wtD7f\r\n"
    "tk8cS9iHURvNJzokoiyAaMQNHg1G4IkXpq/PTqNqMGgwEgYDVR0TAQH/BAgwBgEB\r\n"
    "/wIBATARBgNVHQ4ECgQIT3tWlvumf2cwEwYDVR0jBAwwCoAIQP089aoIBgswDgYD\r\n"
    "VR0PAQH/BAQDAgIEMBoGA1UdIAEB/wQQMA4wDAYKKwYBBAGC5CUBATAKBggqhkjO\r\n"
    "PQQDAgNJADBGAiEAkb/mSulx8xW7cbl1b7CkrxiOFq6n7xy3o4sxaj2APeoCIQCs\r\n"
    "EkFFa5ROJP0iIRsWII/x45Rb1rbUX+lta8uCNz14JQ==\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_MICA_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIB1DCCAXqgAwIBAgIFAL6ICq4wCgYIKoZIzj0EAwIwOjELMAkGA1UEBhMCVVMx\r\n"
    "CzAJBgNVBAoMAlRJMRIwEAYDVQQDDAlXaVNVTiBNQ0ExCjAIBgNVBAUTATIwIBcN\r\n"
    "MjEwNTI5MjAyMDUwWhgPOTk5OTEyMzEyMzU5NTlaMDsxCzAJBgNVBAYTAlVTMQsw\r\n"
    "CQYDVQQKDAJUSTETMBEGA1UEAwwKV2lTVU4gTUlDQTEKMAgGA1UEBRMBMzBZMBMG\r\n"
    "ByqGSM49AgEGCCqGSM49AwEHA0IABIoDqK7Dh2aNPS1KgR3dL0lwVR8JEddemMrx\r\n"
    "S5J3ok7qyrYcSrfW4xwm+xpOfcTiUredc+UyAkG+HJlyZ0BQVbijajBoMBIGA1Ud\r\n"
    "EwEB/wQIMAYBAf8CAQAwEQYDVR0OBAoECEHbJKKDpOHaMBMGA1UdIwQMMAqACE97\r\n"
    "Vpb7pn9nMA4GA1UdDwEB/wQEAwICBDAaBgNVHSABAf8EEDAOMAwGCisGAQQBguQl\r\n"
    "AQEwCgYIKoZIzj0EAwIDSAAwRQIgPNu16+1bz+sicscEi0cckXgmTp8MdrN7cJiG\r\n"
    "jpn/wd8CIQCujzg6ami/lXsLQULWKD1fDEZZYrGNL9Q583/MdnYN1Q==\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_SERVER_CERTIFICATE_FROM_MICA[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBpDCCAUqgAwIBAgIFAKicjRQwCgYIKoZIzj0EAwIwOzELMAkGA1UEBhMCVVMx\r\n"
    "CzAJBgNVBAoMAlRJMRMwEQYDVQQDDApXaVNVTiBNSUNBMQowCAYDVQQFEwEzMCAX\r\n"
    "DTIxMDUyOTIwMjIzNFoYDzk5OTkxMjMxMjM1OTU5WjAAMFkwEwYHKoZIzj0CAQYI\r\n"
    "KoZIzj0DAQcDQgAExNwiK2lhSvUOoDNnjdEHMrEPLCVcVfIc291Jps5g/e9666rY\r\n"
    "yhV1pMn6bUTNM7HnYQLAapUW3usP/kpAVfYWUaN0MHIwEwYDVR0jBAwwCoAIQdsk\r\n"
    "ooOk4dowDgYDVR0PAQH/BAQDAgOIMCgGA1UdEQEB/wQeMBygGgYIKwYBBQUHCASg\r\n"
    "DjAMBgUrBgEEAQQDEjq8MCEGA1UdJQEB/wQXMBUGCSsGAQQBguQlAQYIKwYBBQUH\r\n"
    "AwEwCgYIKoZIzj0EAwIDSAAwRQIhAOQaDbc0yRGvp86X/NxqbCVkfU4WRpXTkVqj\r\n"
    "FLlq1zREAiBTUQeSA4Ts437SP1eerDdUb7yoJ1TriSR9I36FNsMNXg==\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_SERVER_CERTIFICATE_FROM_MICA_KEY[] = {
    "-----BEGIN PRIVATE KEY-----\r\n"
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgQzuxrW/EIodwhdsG\r\n"
    "EXB0VzASllIiE2YUYh2GH4CQXoqhRANCAATE3CIraWFK9Q6gM2eN0QcysQ8sJVxV\r\n"
    "8hzb3UmmzmD973rrqtjKFXWkyfptRM0zsedhAsBqlRbe6w/+SkBV9hZR\r\n"
    "-----END PRIVATE KEY-----"
};


const uint8_t WISUN_SERVER_CERTIFICATE[] = {
    "-----BEGIN CERTIFICATE-----\r\n"
    "MIIBnDCCAUGgAwIBAgIESmUozDAKBggqhkjOPQQDAjAxMQ4wDAYDVQQKDAVXaVNV\r\n"
    "TjETMBEGA1UEAwwKV2lTVU4gUm9vdDEKMAgGA1UEBRMBMTAgFw0xNzA4MjEwMDA0\r\n"
    "MjBaGA85OTk5MTIzMTIzNTk1OVowADBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA\r\n"
    "BEcZ97gqqNcjNLKzMlnRbl7XWlNFZ1+42QsCBAWEAR8g9nRo9KiTnq//DdLcT8Vl\r\n"
    "afcK82gf3GMjf3nNUy1jbCOjdjB0MBMGA1UdIwQMMAqACED9PPWqCAYLMA4GA1Ud\r\n"
    "DwEB/wQEAwIDiDAqBgNVHREBAf8EIDAeoBwGCCsGAQUFBwgEoBAwDgYIKwYBBAEJ\r\n"
    "AQMEAgIiMCEGA1UdJQEB/wQXMBUGCSsGAQQBguQlAQYIKwYBBQUHAwEwCgYIKoZI\r\n"
    "zj0EAwIDSQAwRgIhAMeYoELP41Sre9ZQdotZAJLnOCcLyd5Q98OIRieX4JeBAiEA\r\n"
    "vXfGcPH4OxN5WNop7gF5BKjqnWpgdHvrsUK1kQNbKPI=\r\n"
    "-----END CERTIFICATE-----"
};

const uint8_t WISUN_SERVER_KEY[] = {
    "-----BEGIN PRIVATE KEY-----\r\n"
    "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgOEY66Wi9AgjQpcBx\r\n"
    "0kQRwE7auj6CjWQnstUoiUxMpGuhRANCAARHGfe4KqjXIzSyszJZ0W5e11pTRWdf\r\n"
    "uNkLAgQFhAEfIPZ0aPSok56v/w3S3E/FZWn3CvNoH9xjI395zVMtY2wj\r\n"
    "-----END PRIVATE KEY-----"
};


#endif /* WISUN_TEST_CERTIFICATES_H_ */
