const gruvboxColors = {
  'gruvbox-dark0': '#282828',
  'gruvbox-dark0_hard': '#1d2021',
  'gruvbox-dark0_soft': '#32302f',
  'gruvbox-dark1': '#3c3836',
  'gruvbox-dark2': '#504945',
  'gruvbox-dark3': '#665c54',
  'gruvbox-dark4': '#7c6f64',
  'gruvbox-light0': '#fbf1c7',
  'gruvbox-light0_hard': '#f9f5d7',
  'gruvbox-light0_soft': '#f2e5bc',
  'gruvbox-light1': '#ebdbb2',
  'gruvbox-light2': '#d5c4a1',
  'gruvbox-light3': '#bdae93',
  'gruvbox-light4': '#a89984',
  'gruvbox-bg': '#282828',
  'gruvbox-fg': 'f2e5bc',
  'gruvbox-gray': '#928374',
  'gruvbox-red': '#cc241d',
  'gruvbox-light-red': '#fb4934',
  'gruvbox-faded-red': '#9d0006',
  'gruvbox-green': '#98971a',
  'gruvbox-light-green': '#b8bb26',
  'gruvbox-faded-green': '#79740e',
  'gruvbox-yellow': '#d79921',
  'gruvbox-light-yellow': '#fabd2f',
  'gruvbox-faded-yellow': '#b57614',
  'gruvbox-blue': '#458588',
  'gruvbox-light-blue': '#83a598',
  'gruvbox-faded-blue': '#076678',
  'gruvbox-purple': '#b16286',
  'gruvbox-light-purple': '#d3869b',
  'gruvbox-faded-purple': '#8f3f71',
  'gruvbox-aqua': '#689d6a',
  'gruvbox-light-aqua': '#8ec07c',
  'gruvbox-faded-aqua': '#427b58',
  'gruvbox-orange': '#d65d0e',
  'gruvbox-light-orange': '#fe8019',
  'gruvbox-faded-orange': '#af3a03',
};

const colorScheme = {
  bg: gruvboxColors['gruvbox-dark0'],
  bg0h: gruvboxColors['gruvbox-dark0_hard'],
  bg0: gruvboxColors['gruvbox-dark0'],
  bg1: gruvboxColors['gruvbox-dark1'],
  bg2: gruvboxColors['gruvbox-dark2'],
  bg3: gruvboxColors['gruvbox-dark3'],
  bg4: gruvboxColors['gruvbox-dark4'],
  fg0: gruvboxColors['gruvbox-light0'],
  white: '#FFFFFF',
  redDark: gruvboxColors['gruvbox-red'],
  red: gruvboxColors['gruvbox-light-red'],
  green: gruvboxColors['gruvbox-light-green'],
  greenDark: gruvboxColors['gruvbox-green'],
  yellow: gruvboxColors['gruvbox-light-yellow'],
  blue: gruvboxColors['gruvbox-light-blue'],
  purple: gruvboxColors['gruvbox-light-purple'],
  aqua: gruvboxColors['gruvbox-light-aqua'],
  gray: gruvboxColors['gruvbox-gray'],
  orange: gruvboxColors['gruvbox-orange'],
  yellowDark: gruvboxColors['gruvbox-yellow'],
};

export default colorScheme;
