const tiColorScheme = {
  white: '#FFFFFF',
  bg: '#ECECEC',
  // bg0h: gruvboxColors["gruvbox-dark0_hard"],
  bg0: '#ECECEC',
  bg1: '#EBF6F7',
  bg2: '#F7F7F7',
  bg3: '#FFFFFF',
  // bg4: gruvboxColors["gruvbox-dark4"],
  // fg0: gruvboxColors["gruvbox-light0"],
  red: '#CC0000',
  redDark: '#AE0000',
  green: '#44BB55',
  greenDark: '#1c4d23',
  yellow: '#fabd2f',
  yellowDark: '#d79921',
  orange: '#FE8019',
  blue: '#007C8C',
  // purple: gruvboxColors["gruvbox-light-purple"],
  // aqua: gruvboxColors["gruvbox-light-aqua"],
  gray: '#555555',
  grayLight: '#98999B',
  // orange: gruvboxColors["gruvbox-orange"],
};

export default tiColorScheme;
