set(SOURCES_COMMON_NANOSTACK

    # Platform port layer
    src/platform_layer_port/mbednanostack2linux/platform/ns_trace.c
    src/platform_layer_port/mbednanostack2linux/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_interrupt.cpp
    src/platform_layer_port/mbednanostack2linux/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_random.c
    src/platform_layer_port/mbednanostack2linux/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_timer_polling.cpp
    src/platform_layer_port/mbednanostack2linux/nanostack/nanostack-hal-mbed-cmsis-rtos/linux_polling_timer.cpp
    src/platform_layer_port/mbednanostack2linux/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop_mutex.c
    src/platform_layer_port/mbednanostack2linux/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_event_loop.c
    src/platform_layer_port/mbednanostack2linux/nanostack/nanostack-hal-mbed-cmsis-rtos/ns_hal_init.cpp
    src/platform_layer_port/mbednanostack2linux/nanostack/nanostack-hal-mbed-cmsis-rtos/arm_hal_fhss_timer.c
    src/platform_layer_port/mbednanostack2linux/platform/misc.c
    src/platform_layer_port/mbednanostack2linux/platform/alarm.c
    # src/platform_layer_port/mbedtls2linux/platform/mbed_trng_alt.c
    src/platform_layer_port/ncp_interface2linux/ncp_socket.cpp

    # NV
    src/lprf-dallas-wisunfan/source/ti/common/nv/nvocmp.c
    src/lprf-dallas-wisunfan/source/ti/common/nv/crc.c

    # Wi-SUN MAC deps
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/wisunfan_mac/services/saddr/saddr.c
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/wisunfan_mac/common/osal_port/timac_fhss_config.c

    # Files from RCP
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/rcp/rcp_host_helpers.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bbr_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/mbed-mesh-api/source/wisun_tasklet.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/mac_header_helper_functions.c
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/rcp/rcp_security_mib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/MAC/IEEE802_15_4/sw_mac.c
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/rcp/rcp_mcps_sap.c
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/rcp/rcp_mlme.c
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/rcp/rcp_host.c
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/rcp/rcp_queue.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/platform_util.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/threading.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/mbed-client-randlib/source/randLIB.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/nanostack-libservice/source/IPv6_fcf_lib/ip_fsc.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/nanostack-libservice/source/libBits/common_functions.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/nanostack-libservice/source/libList/ns_list.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/nanostack-libservice/source/libip6string/ip6tos.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/nanostack-libservice/source/libip6string/stoip6.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/nanostack-libservice/source/nsdynmemLIB/nsdynmemLIB.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_se.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_slot_management.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/psa_its_file.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/aes.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/aesni.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/arc4.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/aria.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/asn1parse.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/asn1write.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/base64.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/bignum.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/blowfish.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/camellia.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ccm.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/chacha20.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/chachapoly.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/cipher.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/cipher_wrap.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/cmac.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ctr_drbg.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/des.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/dhm.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ecdh.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ecdsa.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ecjpake.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ecp.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ecp_curves.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/entropy.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/entropy_poll.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/gcm.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/havege.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/hkdf.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/hmac_drbg.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/md.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/md2.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/md4.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/md5.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/memory_buffer_alloc.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/nist_kw.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/oid.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/padlock.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/pem.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/pk.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/pk_wrap.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/pkcs12.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/pkcs5.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/pkparse.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/pkwrite.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/platform.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/poly1305.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ripemd160.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/rsa.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/rsa_internal.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/sha1.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/sha256.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/sha512.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/timing.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/xtea.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/certs.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/debug.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/error.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/pkcs11.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ssl_cache.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ssl_ciphersuites.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ssl_cli.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ssl_cookie.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ssl_srv.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ssl_msg.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ssl_ticket.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/ssl_tls.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/version.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/version_features.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/x509.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/x509_create.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/x509_crl.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/x509_crt.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/x509_csr.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/x509write_crt.c
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/src/x509write_csr.c
    # src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/mbed-mesh-api/source/ethernet_tasklet.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/mbed-mesh-api/source/mesh_system.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic/network_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic/protocol_6lowpan.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic/protocol_6lowpan_bootstrap.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Bootstraps/Generic/protocol_6lowpan_interface.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Fragmentation/cipv6_fragmenter.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode/6lowpan_iphc.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode/iphc_compress.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode/iphc_decompress.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/IPHC_Decode/lowpan_context.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_helper.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_ie_lib.c
    # src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_pairwise_key.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ND/nd_router_object.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/NVM/nwk_nvm.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/adaptation_interface.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_cfg_settings.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_bootstrap.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_common.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_auth_relay.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_pdu.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_relay.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_eapol_relay_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_empty_functions.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_ie_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_llc_data_service.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_management_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_mpx_header.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_neighbor_class.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_key_storage.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_time.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_auth.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_controller.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_nvm_data.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_nvm_store.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_supp.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_pae_timers.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_stats.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/ws/ws_test_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/BorderRouter/border_router.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6_prefix.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/icmpv6_radv.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/ipv6.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/ipv6_flow.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/ipv6_fragmentation.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/ipv6_resolution.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/mld.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/tcp.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Common_Protocols/udp.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Core/buffer_dyn.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Core/ns_address_internal.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Core/ns_monitor.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Core/ns_socket.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Core/sockbuf.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/DHCPv6_Server/DHCPv6_Server_service.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/DHCPv6_client/dhcpv6_client_service.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/MAC/rf_driver_storage.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/MLE/mle.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/MLE/mle_tlv.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/MPL/mpl.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/protocol_core.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/protocol_core_sleep.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/protocol_stats.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/NWK_INTERFACE/protocol_timer.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/RPL/rpl_control.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/RPL/rpl_data.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/RPL/rpl_downward.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/RPL/rpl_mrhof.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/RPL/rpl_objective.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/RPL/rpl_of0.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/RPL/rpl_policy.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/RPL/rpl_upward.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/Common/security_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/PANA/eap_protocol.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/PANA/pana.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/PANA/pana_avp.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/PANA/pana_client.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/PANA/pana_eap_header.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/PANA/pana_header.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/PANA/pana_relay_table.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/PANA/pana_server.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/TLS/tls_ccm_crypt.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/TLS/tls_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/eapol/eapol_helper.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/eapol/kde_helper.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_addr.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_eapol_pdu_if.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/kmp/kmp_socket_if.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/avp_helper.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/radius_sec_prot/radius_client_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/radius_eap_tls_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/auth_eap_tls_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/eap_tls_sec_prot_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/eap_tls_sec_prot/supp_eap_tls_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot/auth_fwh_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/fwh_sec_prot/supp_fwh_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot/auth_gkh_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/gkh_sec_prot/supp_gkh_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/key_sec_prot/key_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_certs.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_keys.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/sec_prot_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Security/protocols/tls_sec_prot/tls_sec_prot_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/CCM_lib/ccm_security.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/CCM_lib/mbedOS/aes_mbedtls.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/CCM_lib/mbedOS/aes_mbedtls_adapter.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/Neighbor_cache/neighbor_cache.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/SHA256_Lib/ns_sha256.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/SHA256_Lib/shalib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/Trickle/trickle.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/blacklist/blacklist.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/etx/etx.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/fhss/channel_list.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/fnv_hash/fnv_hash.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/hmac/hmac_md.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/ieee_802_11/ieee_802_11.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/load_balance/load_balance.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mac_neighbor_table/mac_neighbor_table.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/mdns/fnet_mdns.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/services/poll/fnet_poll.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/stack/fnet_stdlib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/ns_fnet_events.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/ns_fnet_port.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/ns_mdns_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service_buffer.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service_frame_counter_table.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service_interface.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service_security.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/nd_proxy/nd_proxy.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/nist_aes_kw/nist_aes_kw.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/pan_blacklist/pan_blacklist.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/utils/isqrt.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/utils/ns_conf.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/utils/ns_crc.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/utils/ns_file_system.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/whiteboard/whiteboard.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/random_early_detection/random_early_detection.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/nanostack-libservice/source/nsdynmemtracker/nsdynmem_tracker_lib.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/ipv6_stack/ipv6_routing_table.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/ipv6_stack/protocol_ipv6.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libDHCPv6/dhcp_service_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_server.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libDHCPv6/libDHCPv6_vendordata.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/multicast_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/net_dns.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/net_6lowpan_parameter_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/net_ipv6.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/net_load_balance.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/net_mle.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/net_rpl.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/net_short_address_extension.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/net_test.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/ns_net.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/libNET/src/socket_api.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack-eventloop/source/event.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack-eventloop/source/ns_timeout.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack-eventloop/source/ns_timer.cpp
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack-eventloop/source/system_timer.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/frameworks/mbed-trace/source/mbed_trace.c
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/lib/spinel/spinel.c
    
    # Files added in manually -- generally related to MAC code. This section liable to change based on LCs changes to the RCP framework to use Nanostack MAC
    # src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/MAC/ethernet/ethernet_mac_api.c
    # end files added in manually
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_se.c 
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_slot_management.c 
    src/lprf-dallas-wisunfan/source/third_party/ti_wisunfan/mbedtls/platform/COMPONENT_PSA_SRV_IMPL/psa_crypto_storage.c 
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/beacon_handler.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/MAC/mac_data_poll.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/6LoWPAN/Mesh/mesh.c
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/ieee_802_11/ieee_802_11.c 
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mdns/fnet/fnet_stack/stack/fnet_stdlib.c 
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service.c 
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service_buffer.c 
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service_frame_counter_table.c 
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service_interface.c 
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/mle_service/mle_service_security.c 
    src/lprf-dallas-wisunfan/source/third_party/mbed/nanostack/sal-stack-nanostack/source/Service_Libs/nist_aes_kw/nist_aes_kw.c 

    # CPP Code
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/ncp/ncp_base_mtd.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/ncp/changed_props_set.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/ncp/ncp_base.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/ncp/ncp_base_dispatcher.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/lib/hdlc/hdlc.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/lib/spinel/spinel_buffer.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/lib/spinel/spinel_decoder.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/lib/spinel/spinel_encoder.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/api/message_api.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/api/logging_api.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/api/instance_api.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/crc16.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/instance.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/logging.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/message.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/notifier.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/string.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/tasklet.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/timer.cpp
    src/lprf-dallas-wisunfan/source/ti/ti_wisunfan/ncp_interface/src/core/common/tlvs.cpp
)